### ISSUE TITLE
Running app locally results in "Unable to read the configuration"

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio-vertx-boosters/vertx-configmap-booster-redhat#14]
Clone& run app locally via `mvn compile vertx:run`

ERROR: Pressing "Invoke" button results in "Unable to read the configuration":

![image](https://user-images.githubusercontent.com/1461122/39537873-2c121840-4e3b-11e8-9b54-d6b9cd95e8fb.png)

version of app `v13`
related openshift.io issue - https://github.com/openshiftio/openshift.io/issues/2988

**Comment by cescoffier** [comment]
Let me try a few things, I may have a (bad) solution.

**Comment by cescoffier** [comment]
Fixed in master. Actually not a bad approach.
